export const BOOKS_MAP_HTML = {
    "001": "/books/genesis.html",
    "002": "/books/exodus.html",
    "003": "/books/leviticus.html",
    "004": "/books/numbers.html",
    "005": "/books/deuteronomy.html",
    "006": "/books/joshua.html",
    "007": "/books/judges.html",
    "008": "/books/ruth.html",
    "009": "/books/1 samuel.html",
    "010": "/books/2 samuel.html",
    "011": "/books/1 kings.html",
    "012": "/books/2 kings.html",
    "013": "/books/1 chronicles.html",
    "014": "/books/2 chronicles.html",
    "015": "/books/ezra.html",
    "016": "/books/nehemiah.html",
    "017": "/books/esther.html",
    "018": "/books/job.html",
    "019": "/books/psalms.html",
    "020": "/books/proverbs.html",
    "021": "/books/ecclesiastes.html",
    "022": "/books/song_of_solomon.html",
    "023": "/books/isaiah.html",
    "024": "/books/jeremiah.html",
    "025": "/books/lamentation.html",
    "026": "/books/ezekiel.html",
    "027": "/books/daniel.html",
    "028": "/books/hosea.html",
    "029": "/books/joel.html",
    "030": "/books/amos.html",
    "031": "/books/obadiah.html",
    "032": "/books/jonah.html",
    "033": "/books/micah.html",
    "034": "/books/nahum.html",
    "035": "/books/habakkuk.html",
    "036": "/books/zephaniah.html",
    "037": "/books/haggai.html",
    "038": "/books/zechariah.html",
    "039": "/books/malachi.html",
    "040": "/books/matthew.html",
    "041": "/books/mark.html",
    "042": "/books/luke.html",
    "043": "/books/john.html",
    "044": "/books/acts.html",
    "045": "/books/romans.html",
    "046": "/books/1 corinthians.html",
    "047": "/books/2 corinthians.html",
    "048": "/books/galatians.html",
    "049": "/books/ephesians.html",
    "050": "/books/philippians.html",
    "051": "/books/colossians.html",
    "052": "/books/1 thessalonias.html",
    "053": "/books/2 thessalonias.html",
    "054": "/books/1 timothy.html",
    "055": "/books/2 timothy.html",
    "056": "/books/titus.html",
    "057": "/books/philemon.html",
    "058": "/books/hebrews.html",
    "059": "/books/james.html",
    "060": "/books/1 peter.html",
    "061": "/books/2 peter.html",
    "062": "/books/1 john.html",
    "063": "/books/2 john.html",
    "064": "/books/3 john.html",
    "065": "/books/jude.html",
    "066": "/books/revelation.html"
}